# Site settings
title:       Chad Mayfield
email:       info@chadmayfield.com 
author:      Chad Mayfield
description: "The personal website of Chad Mayfield, husband, father, engineer, hacker, and all around nice guy!"
baseurl:     ""
url:         "http://chadmayfield.com"
date_format: "%b %-d, %Y"

# Google analytics
# Google services
google_analytics: UA-79070913-1
google_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: chadmayfield

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: chadmayfield
bitbucket_username:
stackoverflow_id:
twitter_username: chadrmayfield
google_plus_id: 
linkedin_username: chadmayfield
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
